version: '3'
services:
  draxit:
    container_name: draxit
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - MONGODB=mongodb://mongo_user:mongo_password@mongo:27017/draxit?authSource=admin
      - PORT=3000
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=draxit
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: